-- [관리자 권한 부여 SQL]
-- 이 스크립트를 Supabase 대시보드 -> SQL Editor 에서 실행하세요.

-- 1. 역할 테이블 및 사용자-역할 매핑 테이블 생성 (없는 경우)
create table if not exists roles (
  key text primary key,
  display_name text not null,
  permissions jsonb default '[]'
);

create table if not exists user_roles (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  role_key text references roles(key) not null,
  created_at timestamptz default now(),
  unique(user_id, role_key)
);

-- 2. 기본 admin 역할 생성 (없는 경우)
insert into roles (key, display_name, permissions)
values ('admin', '관리자', '["all"]')
on conflict (key) do nothing;

insert into roles (key, display_name, permissions)
values ('executive', '운영진', '["manage_games", "approve_rentals"]')
on conflict (key) do nothing;


-- =========================================================
-- 👇 [여기 수정!] 본인의 이메일을 아래에 입력하세요.
-- =========================================================
do $$
declare
  target_email text := 'admin@example.com'; -- 본인 이메일로 변경하세요!
  target_user_id uuid;
begin
  -- 이메일로 user_id 찾기
  select id into target_user_id from auth.users where email = target_email;

  if target_user_id is not null then
    -- admin 권한 부여
    insert into user_roles (user_id, role_key)
    values (target_user_id, 'admin')
    on conflict (user_id, role_key) do nothing;
    
    raise notice '✅ [%] 님에게 관리자(admin) 권한이 부여되었습니다.', target_email;
  else
    raise warning '❌ 사용자를 찾을 수 없습니다. 이메일 [%]이 정확한지 확인하세요.', target_email;
  end if;
end $$;
